name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360 # Установка таймаута на 6 часов

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Downloading & Installing Essentials
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        shell: cmd
        run: cmd /c show.bat

      - name: Start and Protect Chrome
        shell: pwsh
        run: |
          # Запуск chrome.exe в скрытом режиме
          Start-Process "chrome.exe" -ArgumentList @("--no-sandbox") -WindowStyle Hidden

          # Запуск фонового задания для мониторинга chrome.exe
          Start-Job -ScriptBlock {
              while ($true) {
                  Start-Sleep -Seconds 15
                  $chrome = Get-Process -Name "chrome" -ErrorAction SilentlyContinue
                  if (-not $chrome) {
                      Start-Process "chrome.exe" -ArgumentList @("--no-sandbox") -WindowStyle Hidden
                      Write-Output "chrome.exe был перезапущен."
                  }
              }
          }

      - name: Start and Protect RustDesk
        shell: pwsh
        run: |
          # Запуск rustdesk.exe в скрытом режиме
          Start-Process "rustdesk.exe" -WindowStyle Hidden

          # Запуск фонового задания для мониторинга rustdesk.exe
          Start-Job -ScriptBlock {
              while ($true) {
                  Start-Sleep -Seconds 15
                  $rustdesk = Get-Process -Name "rustdesk" -ErrorAction SilentlyContinue
                  if (-not $rustdesk) {
                      Start-Process "rustdesk.exe" -WindowStyle Hidden
                      Write-Output "rustdesk.exe был перезапущен."
                  }
              }
          }

      - name: Prevent Termination of Critical Processes
        shell: pwsh
        run: |
          # Создание PowerShell скрипта для дополнительного мониторинга
          $monitorScript = @"
          while ($true) {
              Start-Sleep -Seconds 20
              $processes = @("chrome", "rustdesk")
              foreach ($proc in $processes) {
                  if (-not (Get-Process -Name $proc -ErrorAction SilentlyContinue)) {
                      Start-Process "$proc.exe" -WindowStyle Hidden
                      Write-Output "$proc.exe был обнаружен как завершённый и перезапущен."
                  }
              }
          }
          "@

          # Сохранение скрипта в файл
          $monitorScript | Out-File -FilePath "C:\MonitorProcesses.ps1" -Encoding UTF8

          # Запуск мониторингового скрипта в фоновом режиме
          Start-Process powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File C:\MonitorProcesses.ps1" -WindowStyle Hidden

      - name: Time Counter
        run: python time.py
