name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360  # Установка таймаута на 6 часов (360 минут)
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.bat?rlkey=snr74vv1vr8k5suujugvrhjtm&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Start Chrome and Make It Resilient
        run: |
          Start-Process "chrome.exe" -ArgumentList @("--no-sandbox") -WindowStyle Hidden
          
          # Запуск скрипта-контроллера в фоновом режиме
          Start-Job -ScriptBlock {
              while ($true) {
                  Start-Sleep -Seconds 10
                  $chrome = Get-Process -Name "chrome" -ErrorAction SilentlyContinue
                  if (-not $chrome) {
                      Start-Process "chrome.exe" -ArgumentList @("--no-sandbox") -WindowStyle Hidden
                  }
              }
          }

      - name: Prevent Termination of Critical Processes
        run: |
          # Создание службы для защиты процессов
          $serviceScript = @"
          while ($true) {
              Start-Sleep -Seconds 5
              $proc = Get-Process -Name "chrome" -ErrorAction SilentlyContinue
              if (-not $proc) {
                  Start-Process "chrome.exe" -ArgumentList @("--no-sandbox") -WindowStyle Hidden
              }
          }
          "@
          $serviceScript | Out-File -FilePath "protect.ps1" -Encoding UTF8
          Start-Process powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File protect.ps1" -WindowStyle Hidden

      - name: Time Counter
        run: python time.py
